name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
        django-version: ["<1.9", "<1.10", "<1.11", "<1.12", "<2.1", "<2.2", "<2.3", "<3.1", "<3.2"]
        mjml-version: ["3.3.8", "4.3.1", "4.4.0", "4.5.1", "4.6.3"]
        exclude:
          - python-version: "3.8"
            django-version: "<2.1"
          - python-version: "3.8"
            django-version: "<2.2"
          - python-version: "3.8"
            django-version: "<2.3"
          - python-version: "3.8"
            django-version: "<3.1"
          - python-version: "3.8"
            django-version: "<3.2"
          - python-version: "3.8"
            django-version: "<1.9"
          - python-version: "3.8"
            django-version: "<1.10"
          - python-version: "3.8"
            django-version: "<1.11"
          - python-version: "3.8"
            django-version: "<1.12"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Updated Node.js version to a more recent LTS version

      - name: Create package.json
        run: echo '{}' > package.json

      - name: Install dependencies
        run: |
          npm install -g mjml-http-server@0.0.3
          npm install mjml@${{ matrix.mjml-version }}
          ./node_modules/.bin/mjml --version
          pip install "Django${{ matrix.django-version }}"
          pip install "requests>=2.20.0,<=2.24.0"
          pip install "six"  # Added installation of 'six' package to resolve the missing module
          pip install "urllib3<1.25"  # Ensure compatible urllib3 version is installed to resolve the missing module
          pip install "urllib3[secure]"  # Install urllib3 with secure extras to ensure compatibility

      - name: Run tests
        run: python tools.py test
