name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
        django-version:
          - "Django>=1.4,<1.5"
          - "Django>=1.5,<1.6"
          - "Django>=1.6,<1.7"
          - "Django>=1.7,<1.8"
          - "Django>=1.8,<1.9"
          - "Django>=1.9,<1.10"
          - "Django>=1.10,<1.11"
          - "Django>=1.11,<2.0"
        exclude:
          - python-version: "3.8"
            django-version: "Django>=1.10,<1.11"
          - python-version: "3.8"
            django-version: "Django>=1.11,<2.0"
          - python-version: "3.8"
            django-version: "Django>=1.4,<1.5"
          - python-version: "3.8"
            django-version: "Django>=1.5,<1.6"
          - python-version: "3.8"
            django-version: "Django>=1.6,<1.7"
          - python-version: "3.8"
            django-version: "Django>=1.7,<1.8"
          - python-version: "3.8"
            django-version: "Django>=1.8,<1.9"
          - python-version: "3.8"
            django-version: "Django>=1.9,<1.10"
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coveralls coverage
          pip install django
          if [ -n "${{ matrix.django-version }}" ]; then
            pip install ${{ matrix.django-version }}
          fi
      - name: Run tests
        run: |
          sed -i 's/ugettext_lazy/gettext_lazy/g' your_code_file.py
          coverage run runtests.py
          coverage report -m
      - name: Combine coverage
        run: coverage combine
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls
