name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        with-opt-deps: [false, true]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt pytest
          if [ "${{ matrix.with-opt-deps }}" = "true" ]; then
            pip install cryptography feedparser
          fi
          git clone https://github.com/ProgVal/irctest.git
          echo "y" | pip uninstall limnoria || true

      - name: Install package
        run: python setup.py install

      - name: Configure Python environment
        run: |
          python -c "import sys; sys.set_int_max_str_digits(20000)"

      - name: Run tests
        env:
          PYTHONINTMAXSTRDIGITS: 20000
        run: |
          supybot-test test -v --plugins-dir=./plugins/ --no-network
          if [ "${{ matrix.with-opt-deps }}" = "true" ] && [[ "${{ matrix.python-version }}" =~ ^3\.[4-9] ]]; then
            cd irctest
            pytest --controllers irctest.controllers.limnoria
    continue-on-error: ${{ matrix.with-opt-deps == true }}
