name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -U tox tox-gh-actions
    - name: Install pytest and dependencies
      run: pip install pytest
    - name: Install specific version of typeguard
      run: pip install 'typeguard<3.0.0'
    - name: Run tests
      run: tox
      env:
        TOXENV: py38
    - name: Display Tox logs on failure
      if: failure()
      run: cat .tox/py38/log/py38-0.log
