name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
        django-version: ['django30', 'django31']
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coverage pytest
          pip install beautifulsoup4

      - name: Create tox environment
        run: |
          echo "[tox]" > tox.ini
          echo "envlist = py${{ matrix.python-version }}-django30, py${{ matrix.python-version }}-django31" >> tox.ini
          echo "[testenv]" >> tox.ini
          echo "deps =" >> tox.ini
          echo "    django30: Django>=3.0,<3.1" >> tox.ini
          echo "    django31: Django>=3.1,<3.2" >> tox.ini
          echo "    coverage" >> tox.ini
          echo "    pytest" >> tox.ini
          echo "    beautifulsoup4" >> tox.ini
          echo "    django-jsonfield-backport" >> tox.ini
          echo "commands = coverage run -m unittest discover" >> tox.ini

      - name: Run tests
        env:
          TOX_ENV: py${{ matrix.python-version }}-${{ matrix.django-version }}
        run: tox -r -e $TOX_ENV

      - name: Upload coverage to Codecov
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
