name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install -v

      - name: Update pyproject.toml for deprecated dev-dependencies
        run: |
          sed -i 's/\[tool.poetry.dev-dependencies\]/[tool.poetry.group.dev.dependencies]/' pyproject.toml

      - name: Install specific version of typed_ast
        run: |
          poetry add typed-ast==1.4.3 --allow-prereleases

      - name: Run flake8 on example/
        run: poetry run flake8 example/

      - name: Run flake8 on tests/
        run: poetry run flake8 tests/

      - name: Run Black
        run: poetry run black --check .

      - name: Run tests
        env:
          PYTHONPATH: ""
        run: poetry run pytest

      - name: Fix undefined symbol error
        if: ${{ matrix.python-version == '3.9' }}
        run: |
          pip uninstall -y typed-ast
          pip install typed-ast==1.4.3
