name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Make install_radare2.sh executable
      run: chmod +x ./scripts/install_radare2.sh

    - name: Install project dependencies
      run: |
        ./scripts/install_radare2.sh
        pip install -r python/requirements_ci.txt
        cd python && chmod +x setup.py && ./setup.py install

    - name: Run tests
      run: |
        cd python/test && make tests
      env:
        PYTHONPATH: ${{ github.workspace }}/python
        PATH: ${{ github.workspace }}/scripts:${{ env.PATH }}
