name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install pyusb coverage coveralls pyserial PyYAML tqdm

      - name: Fix YAML Loader Issue
        run: |
          sed -i 's/yaml.load(/yaml.safe_load(/g' $(find . -name "*.py")
          sed -i 's/safe_load(.*Loader=yaml.SafeLoader)/safe_load(/g' $(find . -name "*.py")

      - name: Build
        run: python setup.py build

      - name: Test with coverage
        run: |
          python -m compileall .
          coverage run --source=stcgal -m unittest discover

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls
