name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        django-version: ["1.11", "2.0", "2.1", "2.2", "3.0", "3.1", "3.2"]
        include:
          - python-version: "3.8"
            django-version: "1.11"
          - python-version: "3.8"
            django-version: "2.0"
          - python-version: "3.8"
            django-version: "2.1"
          - python-version: "3.8"
            django-version: "2.2"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run tests
        env:
          TOXENV: py${{ matrix.python-version }}-django${{ matrix.django-version | replace('.', '') }}
        run: tox

  allow_failures:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        django-version: ["4.0"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run tests
        env:
          TOXENV: py${{ matrix.python-version }}-django${{ matrix.django-version | replace('.', '') }}
        run: tox || true
