name: Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.x"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install simplejson minimock coverage pytest
    - name: Run tests
      run: |
        set -e
        # Update the test files to use assertEqual instead of assertEquals
        find . -name "*.py" -exec sed -i 's/assertEquals/assertEqual/g' {} +
        # Update the test files to use assertIn instead of assert_
        find . -name "*.py" -exec sed -i 's/assert_/assertIn/g' {} +
        # Correct the usage of assertIn to assertTrue for assert_ replacements
        find . -name "*.py" -exec sed -i 's/assertIn(\(.*\))/assertTrue(\1 in /g' {} +
        # Ensure the syntax is correct by adding a missing comma
        find . -name "*.py" -exec sed -i 's/\(assertTrue(\(.*\) in \)/\1, /g' {} +
        # Run pytest directly instead of make test
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: pip install simplejson minimock coverage
    - name: Deploy to PyPI
      env:
        TWINE_USERNAME: gpodder
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install --upgrade twine
        twine upload dist/*
