name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', 'pypy-3.8']
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -U 'setuptools>=18.5' 'pip>=6.0' 'wheel'
          pip install -e .
        env:
          CFLAGS: "-Wno-narrowing"

      - name: Install specific greenlet version
        run: pip install greenlet==1.1.0
        # Add a condition to skip this step for Python 3.10
        if: matrix.python-version != '3.10'

      - name: Run tests
        run: python runtests.py
