name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
        toxenv:
          - py38
          - py39
          - black
          - pep8py3
          - doc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install tox codecov

      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox -e ${{ matrix.toxenv }}

      - name: Upload coverage to Codecov
        if: success() && (matrix.toxenv == 'py38' || matrix.toxenv == 'py39')
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: codecov
