name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
        toxenv:
          - py38
          - py39
          - qa
          - doc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install tox

      - name: Create a default tox.ini
        run: |
          echo "[tox]" > tox.ini
          echo "envlist = py38, py39, qa, doc" >> tox.ini
          echo "[testenv]" >> tox.ini
          echo "deps = pytest" >> tox.ini
          echo "commands = pytest" >> tox.ini

      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: |
          if [[ "${{ matrix.toxenv }}" == "py38" && "${{ matrix.python-version }}" != "3.8" ]]; then
            echo "Skipping py38 environment for Python ${{ matrix.python-version }}"
            exit 0
          fi
          if [[ "${{ matrix.toxenv }}" == "py39" && "${{ matrix.python-version }}" != "3.9" ]]; then
            echo "Skipping py39 environment for Python ${{ matrix.python-version }}"
            exit 0
          fi
          tox -e ${{ matrix.toxenv }} -v || exit 1
