name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install dependencies
        run: |
          sudo apt install python3-pip
          pip install -r requirements.txt
          pip install tox

      - name: Check for tox configuration
        run: |
          if [ ! -f tox.ini ]; then
            echo "tox.ini file not found"
            exit 1
          fi
          if ! grep -q '\[tox\]' tox.ini; then
            echo "[tox] section not found in tox.ini"
            exit 1
          fi

      - name: Run tests
        run: tox
        env:
          TOXENV: py
        continue-on-error: true

      - name: List files for debugging
        if: failure()
        run: ls -la

      - name: Print tox.ini for debugging
        if: failure() && -f tox.ini
        run: cat tox.ini
