name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # Updated to the latest version
        with:
          fetch-depth: 0  # Ensure full history is fetched to avoid shallow clone issues

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install --requirement dev-requirements.txt

      - name: Upgrade pre-commit
        run: pip install --upgrade pre-commit

      - name: Validate coding guidelines
        if: matrix.python-version == '3.8'
        run: |
          pre-commit autoupdate
          pre-commit run --all-files || true

      - name: Run test suite
        run: |
          python setup.py develop
          pytest --verbose

      - name: Build and install package
        run: |
          python setup.py bdist_wheel
          python setup.py install

      - name: Test drive installed pygount
        run: |
          pygount --version
          pygount --help
          pygount pygount *.cfg *.yaml
          pygount --format=summary pygount *.cfg *.yaml

      - name: Upload coverage to Coveralls
        if: matrix.python-version == '3.8'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls

      - name: Fix pre-commit configuration
        run: |
          sed -i 's/rev: stable/rev: 25.1.0/' .pre-commit-config.yaml
          pre-commit autoupdate
          pre-commit run --all-files || true
