name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        toxenv: [py38-dj32, py39-dj32, py310-dj32]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage codecov coveralls tox
    - name: Run fake server
      run: ./bin/fake-server &
    - name: Run tests
      run: tox
      env:
        TOXENV: ${{ matrix.toxenv }}
        PYTHONPATH: ${{ matrix.python-version }}
    - name: Upload coverage to Coveralls
      if: ${{ matrix.toxenv == 'py310-dj32' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls
    - name: Upload coverage to Codecov
      if: ${{ matrix.toxenv == 'py310-dj32' }}
      run: codecov

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && contains(github.event.head_commit.message, 'v')
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Build and publish
      env:
        TOXENV: py310-dj32
        TWINE_USERNAME: apsl
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        tox
        python setup.py sdist bdist_wheel
        twine upload dist/*
