name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', 'pypy-3.8']
        include:
          - python-version: '3.8'
            toxenv: py38-cover
          - python-version: '3.8'
            toxenv: coverage
          - python-version: '3.8'
            toxenv: docs
          - python-version: '3.8'
            toxenv: py38-pyramid14
          - python-version: '3.8'
            toxenv: py38-pyramid19
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install tox
      - name: Run tests
        run: |
          if [ -z "${{ matrix.toxenv }}" ]; then
            TOXENV=py${{ matrix.python-version }}
          else
            TOXENV=${{ matrix.toxenv }}
          fi
          tox -e $TOXENV

  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
