name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          fail-on-cache-miss: false

      - name: Install dependencies
        run: CFLAGS="-O0" pip install . --upgrade

      - name: List directory contents
        run: ls -la

      - name: Run tests
        run: |
          chmod +x ./runtests.sh
          ./runtests.sh
        # Remove or update the working-directory line based on the actual location of runtests.sh
        # working-directory: path/to/your/scripts
