name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', 'pypy-3.8']
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox-gh-actions codecov

      - name: Run tests
        run: tox

      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          VERSION="python_${{ matrix.python-version }}" &&
          VERSION="${VERSION//[^[:alnum:]]/}" &&
          codecov --token=${{ secrets.CODECOV_TOKEN }} --required --flags $VERSION --retry 5 --retry-delay 30
