name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "pypy-3.8"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -e .
        pip install requests pytest-cov coveralls
        pip install mock

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Start Docker services
      run: |
        docker-compose -f tests/config/docker-compose.yml up -d
        sleep 120
        if [ -f ./tests/config/bootstrap ]; then
          chmod +x ./tests/config/bootstrap
          ./tests/config/bootstrap
        else
          echo "Bootstrap script not found, skipping."
        fi

    - name: Run tests
      run: pytest -v --cov=pygelf tests/

    - name: Stop Docker services
      if: always()
      run: docker-compose -f tests/config/docker-compose.yml down

    - name: Upload coverage to Coveralls
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: coveralls
