name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', 'pypy-3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools>=39.2.0 wheel
        pip install numpy==1.15.4 scipy matplotlib>=3 cython>=0.28
        python setup.py develop
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-distutils
        sudo apt-get install -y python3-dev
        sudo apt-get install -y build-essential
        sudo apt-get install -y gfortran
        sudo apt-get install -y libpython3-dev
        sudo apt-get install -y libatlas-base-dev
    - name: Run tests
      run: python setup.py test
